services:
  - type: web
    name: springboot-app
    env: java
    plan: free
    region: oregon
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: SERVER_PORT
        value: 8080
