pipeline {
    agent any
    tools {
        maven 'maven'
    }
    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/ingenierIa-y-calidad-de-software-taller/Taller-Demo-CICD.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                dir('ci-taller-demo') {
                    sh 'mvn clean package'
                 }
            }
        }


         stage('Confirmar despliegue') {
            steps {
                script {
                    def userInput = input(
                                id: 'DespliegueConfirmacion', message: '¿Deseas desplegar a producción?', parameters: [
                                    choice(choices: ['Sí', 'No'], description: 'Selecciona una opción', name: 'Desplegar')
                                ]
                            )

                            if (userInput == 'No') {
                        error("El despliegue ha sido cancelado por el usuario.")
                            }
                        }
                    }
                }

       stage('Deploy') {
            steps {
                dir('ci-taller-demo') {
                    // Detenemos contenedor si ya existe
                        sh '''
                            docker stop demo-app || true
                            docker rm demo-app || true
                            docker rmi demo-app || true
                        '''
                        // Build de imagen
                        sh 'docker build -t demo-app .'
                        // Run del contenedor
                        sh 'docker run -d --name demo-app -p 8082:8080 demo-app'
                    }
                }
            }
        }



     post {

        always {
            junit 'ci-taller-demo/target/surefire-reports/*.xml'

                script {
                def result = sh(script: '''
                        PASSED=0
                        FAILED=0
                        SKIPPED=0

                        for file in ci-taller-demo/target/surefire-reports/*.xml; do
                            [ -f "$file" ] || continue
                            PASSED=$((PASSED + $(grep -o 'testsuite.*tests="\\?\\([0-9]\\+\\)"' "$file" | sed -E 's/.*tests="([0-9]+)".*/\\1/')))
                            FAILED=$((FAILED + $(grep -o 'failures="\\?\\([0-9]\\+\\)"' "$file" | sed -E 's/.*failures="([0-9]+)".*/\\1/')))
                            SKIPPED=$((SKIPPED + $(grep -o 'skipped="\\?\\([0-9]\\+\\)"' "$file" | sed -E 's/.*skipped="([0-9]+)".*/\\1/')))
                        done

                        echo "Tests: $PASSED, Fallos: $FAILED, Saltados: $SKIPPED"
                    ''', returnStdout: true).trim()

                    env.TEST_RESULT_MESSAGE = result
                }
            }


        success {
                withCredentials([
                string(credentialsId: 'TELEGRAM_BOT_TOKEN', variable: 'BOT_TOKEN'),
                string(credentialsId: 'TELEGRAM_CHAT_ID', variable: 'CHAT_ID')
            ]) {
                    sh """
                    curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \\
                    -d chat_id=${CHAT_ID} \\
                    -d text="✅ Éxito: Pipeline completado correctamente en Jenkins. \\n📊 ${TEST_RESULT_MESSAGE}"
                """
            }
        }

        failure {
                withCredentials([
                string(credentialsId: 'TELEGRAM_BOT_TOKEN', variable: 'BOT_TOKEN'),
                string(credentialsId: 'TELEGRAM_CHAT_ID', variable: 'CHAT_ID')
            ]) {
                    sh """
                    curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \\
                    -d chat_id=${CHAT_ID} \\
                    -d text="❌ Error: Falló el pipeline en Jenkins. Revisar logs. \\n📊 ${TEST_RESULT_MESSAGE}"
                """
            }
        }
    }

}
